
---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.4.2
  - name: cron-resource
    type: docker-image
    source:
      repository: cftoolsmiths/cron-resource
      # use latest as no other recent tag available
resources:
jobs:
#      - get: bosh-stemcell
#        version: { version: ((stemcell-version)) }
#        trigger: true
#        attempts: 2
- name: this-is-an-empty-pipeline
