---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource
      tag: 3
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.4.2
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
      tag: release-v0.0.3
resources:
jobs:
- name: this-is-an-empty-pipeline
