---
# When offline-mode is enabled, bytes are retrieved from an S3 compliant location, otherwise download from bosh-io
offline-mode:
   boshreleases: false # Choose where boshreleases are downloaded from. Default: false
   stemcells: false # Choose where stemcells are downloaded from. Default: true

default:
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent  # Default: bosh-openstack-kvm-ubuntu-trusty-go_agent
  concourse:
    parallel_execution_limit: 5 # Default: -1, ie unlimited

#<root-deployment-name>: # override per root-deployment
#  concourse:
#    parallel_execution_limit: 10 # Default: -1, ie unlimited
