---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/spruce
    tag: 2792f166a305a329b1d3c4156038490853e3766e
inputs:
  - name: scripts-resource
  - name: config-resource
  - name: templates-resource
outputs:
  - name: check-configuration-result
run:
  path: scripts-resource/concourse/tasks/check_configuration/run.sh
params:
  ROOT_DEPLOYMENT:
  DEPLOYMENT:
  SCAN_PATHS:
  GIT_SUBMODULES:
  LOCAL_SECRETS_SCAN:
