---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/spruce
    tag: b3185eed905c8320013c5d09b6b18cdc0b68ce36
inputs:
  - name: scripts-resource
  - name: config-resource
  - name: templates-resource
outputs:
  - name: check-configuration-result
run:
  path: scripts-resource/concourse/tasks/check_configuration/run.sh
params:
  ROOT_DEPLOYMENT:
  DEPLOYMENT:
  SCAN_PATHS:
  GIT_SUBMODULES:
  LOCAL_SECRETS_SCAN:
