---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: b3185eed905c8320013c5d09b6b18cdc0b68ce36
inputs:
  - name: scripts-resource
  - name: secrets # required for certificates injection
    optional: true
outputs:
  - name: result-dir
run:
  path: ./scripts-resource/concourse/tasks/bosh_variables/run.rb
params:
  BOSH_TARGET:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT:
  BOSH_DEPLOYMENT:
