---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: 7a7678281e1f152183c7359546912df68f298664
inputs:
  - name: scripts-resource
  - name: credentials-resource
  - name: additional-resource
  - name: templates-resource
outputs:
  - name: generated-files
run:
  path: scripts-resource/scripts/cf/push.sh
params:
  GENERATE_DIR:
  BASE_TEMPLATE_DIR:
  SECRETS_DIR:
  CUSTOM_SCRIPT_DIR:
  CF_MANIFEST:
