---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/spruce
    tag: 2792f166a305a329b1d3c4156038490853e3766e
inputs:
  - name: scripts-resource
  - name: credentials-resource
    optional: true
  - name: additional-resource
outputs:
  - name: generated-files
run:
  path: scripts-resource/concourse/tasks/generate_manifest/manifest-lifecycle-generation.sh
params:
  YML_TEMPLATE_DIR:
  SPRUCE_FILE_BASE_PATH:
  YML_FILES:
  SUFFIX:
  CUSTOM_SCRIPT_DIR:
  IAAS_TYPE:
