---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: b3185eed905c8320013c5d09b6b18cdc0b68ce36
inputs:
  - name: scripts-resource
  - name: template-resource
  - name: credentials-resource
    optional: true
  - name: additional-resource
outputs:
  - name: generated-files
run:
  path: scripts-resource/concourse/tasks/post_deploy/run.sh
params:
  CUSTOM_SCRIPT_DIR:
  SECRETS_DIR: