---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: 2792f166a305a329b1d3c4156038490853e3766e
inputs:
  - name: scripts-resource
  - name: secrets
outputs:
  - name: result-dir
run:
  path: ./scripts-resource/concourse/tasks/bosh_cancel_all_tasks/run.rb
params:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_TARGET:
  BOSH_CA_CERT:
